apiVersion: v1
kind: Service
metadata:
  name: feedback-service
spec:
  selector:
    app: feedback-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
